UPDATE customer SET c_delivery_cnt = c_delivery_cnt + _, c_balance = c_balance + CASE c_d_id WHEN _ THEN _ WHEN _ THEN _ WHEN _ THEN _ WHEN _ THEN _ WHEN _ THEN _ WHEN _ THEN _ WHEN _ THEN _ WHEN _ THEN _ WHEN _ THEN _ WHEN _ THEN _ END WHERE (c_w_id = _) AND ((c_d_id, c_id) IN ((_, __more__), __more__))
UPDATE stock SET s_quantity = CASE (s_i_id, s_w_id) WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ ELSE crdb_internal.force_error(_, _) END, s_ytd = CASE (s_i_id, s_w_id) WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ END, s_order_cnt = CASE (s_i_id, s_w_id) WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ END, s_remote_cnt = CASE (s_i_id, s_w_id) WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ END WHERE (s_i_id, s_w_id) IN ((_, __more__), __more__)
SELECT o_id, o_entry_d, o_carrier_id FROM "order" WHERE ((o_w_id = _) AND (o_d_id = _)) AND (o_c_id = _) ORDER BY o_id DESC LIMIT _
SELECT i_price, i_name, i_data FROM item WHERE i_id IN (_, __more__) ORDER BY i_id
SELECT s_quantity, s_ytd, s_order_cnt, s_remote_cnt, s_data, s_dist_02 FROM stock WHERE (s_i_id, s_w_id) IN ((_, __more__), __more__) ORDER BY s_i_id FOR UPDATE
UPDATE customer SET (c_balance, c_ytd_payment, c_payment_cnt, c_data) = (c_balance - (_:::FLOAT8)::DECIMAL, c_ytd_payment + (_:::FLOAT8)::DECIMAL, c_payment_cnt + _, CASE c_credit WHEN _ THEN left((((((c_id::STRING || c_d_id::STRING) || c_w_id::STRING) || (_:::INT8)::STRING) || (_:::INT8)::STRING) || (_:::FLOAT8)::STRING) || c_data, _) ELSE c_data END) WHERE ((c_w_id = _) AND (c_d_id = _)) AND (c_id = _) RETURNING c_first, c_middle, c_last, c_street_1, c_street_2, c_city, c_state, c_zip, c_phone, c_since, c_credit, c_credit_lim, c_discount, c_balance, CASE c_credit WHEN _ THEN left(c_data, _) ELSE _ END
INSERT INTO history(h_c_id, h_c_d_id, h_c_w_id, h_d_id, h_w_id, h_amount, h_date, h_data) VALUES (_, __more__)
INSERT INTO order_line(ol_o_id, ol_d_id, ol_w_id, ol_number, ol_i_id, ol_supply_w_id, ol_quantity, ol_amount, ol_dist_info) VALUES (_, __more__), (__more__)
UPDATE stock SET s_quantity = CASE (s_i_id, s_w_id) WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ ELSE crdb_internal.force_error(_, _) END, s_ytd = CASE (s_i_id, s_w_id) WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ END, s_order_cnt = CASE (s_i_id, s_w_id) WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ END, s_remote_cnt = CASE (s_i_id, s_w_id) WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ END WHERE (s_i_id, s_w_id) IN ((_, __more__), __more__)
SELECT s_quantity, s_ytd, s_order_cnt, s_remote_cnt, s_data, s_dist_05 FROM stock WHERE (s_i_id, s_w_id) IN ((_, __more__), __more__) ORDER BY s_i_id FOR UPDATE
UPDATE stock SET s_quantity = CASE (s_i_id, s_w_id) WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ ELSE crdb_internal.force_error(_, _) END, s_ytd = CASE (s_i_id, s_w_id) WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ END, s_order_cnt = CASE (s_i_id, s_w_id) WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ END, s_remote_cnt = CASE (s_i_id, s_w_id) WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ END WHERE (s_i_id, s_w_id) IN ((_, __more__), __more__)
SELECT c_balance, c_first, c_middle, c_last FROM customer WHERE ((c_w_id = _) AND (c_d_id = _)) AND (c_id = _)
UPDATE warehouse SET w_ytd = w_ytd + _ WHERE w_id = _ RETURNING w_name, w_street_1, w_street_2, w_city, w_state, w_zip
SELECT s_quantity, s_ytd, s_order_cnt, s_remote_cnt, s_data, s_dist_07 FROM stock WHERE (s_i_id, s_w_id) IN ((_, __more__), __more__) ORDER BY s_i_id FOR UPDATE
SELECT d_next_o_id FROM district WHERE (d_w_id = _) AND (d_id = _)
SELECT s_quantity, s_ytd, s_order_cnt, s_remote_cnt, s_data, s_dist_08 FROM stock WHERE (s_i_id, s_w_id) IN ((_, __more__), __more__) ORDER BY s_i_id FOR UPDATE
SELECT sum(ol_amount) FROM order_line WHERE ((ol_w_id = _) AND (ol_d_id = _)) AND (ol_o_id = _)
SELECT s_quantity, s_ytd, s_order_cnt, s_remote_cnt, s_data, s_dist_10 FROM stock WHERE (s_i_id, s_w_id) IN ((_, __more__), __more__) ORDER BY s_i_id FOR UPDATE
UPDATE stock SET s_quantity = CASE (s_i_id, s_w_id) WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ ELSE crdb_internal.force_error(_, _) END, s_ytd = CASE (s_i_id, s_w_id) WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ END, s_order_cnt = CASE (s_i_id, s_w_id) WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ END, s_remote_cnt = CASE (s_i_id, s_w_id) WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ END WHERE (s_i_id, s_w_id) IN ((_, __more__), __more__)
SELECT s_quantity, s_ytd, s_order_cnt, s_remote_cnt, s_data, s_dist_04 FROM stock WHERE (s_i_id, s_w_id) IN ((_, __more__), __more__) ORDER BY s_i_id FOR UPDATE
UPDATE stock SET s_quantity = CASE (s_i_id, s_w_id) WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ ELSE crdb_internal.force_error(_, _) END, s_ytd = CASE (s_i_id, s_w_id) WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ END, s_order_cnt = CASE (s_i_id, s_w_id) WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ END, s_remote_cnt = CASE (s_i_id, s_w_id) WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ END WHERE (s_i_id, s_w_id) IN ((_, __more__), __more__)
DELETE FROM new_order WHERE (no_w_id = _) AND ((no_d_id, no_o_id) IN ((_, __more__), __more__))
UPDATE "order" SET o_carrier_id = _ WHERE (o_w_id = _) AND ((o_d_id, o_id) IN ((_, __more__), __more__)) RETURNING o_d_id, o_c_id
UPDATE stock SET s_quantity = CASE (s_i_id, s_w_id) WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ ELSE crdb_internal.force_error(_, _) END, s_ytd = CASE (s_i_id, s_w_id) WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ END, s_order_cnt = CASE (s_i_id, s_w_id) WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ END, s_remote_cnt = CASE (s_i_id, s_w_id) WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ END WHERE (s_i_id, s_w_id) IN ((_, __more__), __more__)
SELECT c_id, c_balance, c_first, c_middle FROM customer WHERE ((c_w_id = _) AND (c_d_id = _)) AND (c_last = _) ORDER BY c_first ASC
UPDATE stock SET s_quantity = CASE (s_i_id, s_w_id) WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ ELSE crdb_internal.force_error(_, _) END, s_ytd = CASE (s_i_id, s_w_id) WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ END, s_order_cnt = CASE (s_i_id, s_w_id) WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ END, s_remote_cnt = CASE (s_i_id, s_w_id) WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ END WHERE (s_i_id, s_w_id) IN ((_, __more__), __more__)
SELECT w_tax FROM warehouse WHERE w_id = _
UPDATE stock SET s_quantity = CASE (s_i_id, s_w_id) WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ ELSE crdb_internal.force_error(_, _) END, s_ytd = CASE (s_i_id, s_w_id) WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ END, s_order_cnt = CASE (s_i_id, s_w_id) WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ END, s_remote_cnt = CASE (s_i_id, s_w_id) WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ END WHERE (s_i_id, s_w_id) IN ((_, __more__), __more__)
SELECT s_quantity, s_ytd, s_order_cnt, s_remote_cnt, s_data, s_dist_03 FROM stock WHERE (s_i_id, s_w_id) IN ((_, __more__), __more__) ORDER BY s_i_id FOR UPDATE
SELECT c_id FROM customer WHERE ((c_w_id = _) AND (c_d_id = _)) AND (c_last = _) ORDER BY c_first ASC
UPDATE order_line SET ol_delivery_d = _ WHERE (ol_w_id = _) AND ((ol_d_id, ol_o_id) IN ((_, __more__), __more__))
UPDATE district SET d_ytd = d_ytd + _ WHERE (d_w_id = _) AND (d_id = _) RETURNING d_name, d_street_1, d_street_2, d_city, d_state, d_zip
UPDATE district SET d_next_o_id = d_next_o_id + _ WHERE (d_w_id = _) AND (d_id = _) RETURNING d_tax, d_next_o_id
SELECT s_quantity, s_ytd, s_order_cnt, s_remote_cnt, s_data, s_dist_01 FROM stock WHERE (s_i_id, s_w_id) IN ((_, __more__), __more__) ORDER BY s_i_id FOR UPDATE
SELECT no_o_id FROM new_order WHERE (no_w_id = _) AND (no_d_id = _) ORDER BY no_o_id ASC LIMIT _ FOR UPDATE
UPDATE stock SET s_quantity = CASE (s_i_id, s_w_id) WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ ELSE crdb_internal.force_error(_, _) END, s_ytd = CASE (s_i_id, s_w_id) WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ END, s_order_cnt = CASE (s_i_id, s_w_id) WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ END, s_remote_cnt = CASE (s_i_id, s_w_id) WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ WHEN (_, __more__) THEN _ END WHERE (s_i_id, s_w_id) IN ((_, __more__), __more__)
SELECT c_discount, c_last, c_credit FROM customer WHERE ((c_w_id = _) AND (c_d_id = _)) AND (c_id = _)
INSERT INTO new_order(no_o_id, no_d_id, no_w_id) VALUES (_, __more__)
SELECT ol_i_id, ol_supply_w_id, ol_quantity, ol_amount, ol_delivery_d FROM order_line WHERE ((ol_w_id = _) AND (ol_d_id = _)) AND (ol_o_id = _)
SELECT count(DISTINCT s_i_id) FROM order_line JOIN stock ON (s_w_id = _) AND (s_i_id = ol_i_id) WHERE (((ol_w_id = _) AND (ol_d_id = _)) AND (ol_o_id BETWEEN (_) AND (_))) AND (s_quantity < _)